---
- name: User Config Block
  become: true
  tags: users
  block:
    - name: Add user to microk8s group
      ansible.builtin.user:
        name: "{{ microk8s_user }}"
        groups: microk8s
        append: true

    - name: Configure access to .kube caching directory
      ansible.builtin.file:
        path: "/home/{{ microk8s_user }}/.kube"
        owner: "{{ microk8s_user }}"
        group: "{{ microk8s_user }}"
        mode: "0700"
        state: directory

    - name: Generate kubeconfig for remote access
      ansible.builtin.command: microk8s config
      register: microk8s_kubeconfig
      changed_when: false

    - name: Ensure .kube directory exists on development servers
      ansible.builtin.file:
        path: "/home/{{ microk8s_user }}/.kube"
        owner: "{{ microk8s_user }}"
        group: "{{ microk8s_user }}"
        mode: "0700"
        state: directory
      delegate_to: "{{ item }}"
      loop: "{{ development_servers }}"

    - name: Copy kubeconfig to development servers
      ansible.builtin.copy:
        content: "{{ microk8s_kubeconfig.stdout }}"
        dest: "/home/{{ microk8s_user }}/.kube/config"
        owner: "{{ microk8s_user }}"
        group: "{{ microk8s_user }}"
        mode: "0600"
      delegate_to: "{{ item }}"
      loop: "{{ development_servers }}"
      notify: Verify kubectl access on development servers
