---
# handlers file for proxmox
- name: Reload NFS
  become: true
  ansible.builtin.command: 'exportfs -arv'
  changed_when: true # only runs when handler is called

- name: Update initramfs
  become: true
  ansible.builtin.command: 'update-initramfs -u -k all'
  changed_when: true # only runs when handler is called
