---
# Configure local users
- name: User Config Block
  become: true
  tags: users
  block:
    - name: Add sudo group
      ansible.builtin.group:
        name: sudo
        state: present

    - name: Add user groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      with_items: "{{ common_groups }}"

    - name: Add admin users
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        group: "{{ item.gid }}"
        groups: sudo
        append: true
        shell: /bin/bash
        create_home: true
        state: present
      with_items: "{{ admin_users }}"

    - name: Add sudoer rule for admin users
      ansible.builtin.template:
        dest: "/etc/sudoers.d/{{ item.name }}"
        src: sudoer_file.j2
        owner: root
        group: root
        mode: "0440"
        validate: /usr/sbin/visudo -csf %s
      with_items: "{{ admin_users }}"

    - name: Add service users
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        group: "{{ item.gid }}"
        shell: /bin/bash
        create_home: true
        state: present
      with_items: "{{ common_service_users }}"

    - name: Add SSH public keys to authorized users
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.public_ssh_key }}"
        state: present
      with_items: "{{ common_ssh_keys }}"

    - name: Enable fzf bash integration for admin users
      ansible.builtin.lineinfile:
        path: "/home/{{ item.name }}/.bashrc"
        line: '[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash'
        owner: "{{ item.name }}"
        group: "{{ item.gid }}"
        create: false
      with_items: "{{ admin_users }}"
