---
# tasks file for dev role
- name: Package Config
  ansible.builtin.include_tasks: dev_packages.yml
  tags: packages

- name: User Config
  ansible.builtin.include_tasks: dev_users.yml
  tags: users

- name: Service Config
  ansible.builtin.include_tasks: dev_services.yml
  tags: services
