- name: Virtual Machines
  hosts: virtual
  roles:
    - common
    - virtual

- name: Public-facing Machines
  hosts: dmz
  roles:
    - public

- name: SSH Bastion
  hosts: gate
  roles:
    - public_ssh

# As of now, all applications depend on podman role
# - name: DNS & Database Server
#   hosts: library
#   roles:
#     - podman
#     - postgres
#     - pihole

- name: Web Proxy
  hosts: proxy
  roles:
    - podman
    - proxy

- name: Web services
  hosts: bailey
  roles:
    - podman
    - jellyfin
    - foundry

- name: Claude sandbox
  hosts: lab
  roles:
    - dev
