- name: Virtual Machines
  hosts: virtual
  roles:
    - common
    - virtual

- name: Public-facing Machines
  hosts: dmz
  roles:
    - public

- name: SSH Bastion
  hosts: gate
  roles:
    - public_ssh

# As of now, all applications depend on podman role
- name: Web Proxy
  hosts: proxy
  roles:
    - podman
    - proxy

- name: Web Services
  hosts: bailey
  roles:
    - podman
    - jellyfin
    - foundry

- name: Development
  hosts: lab
  roles:
    - dev
